/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/button/index.vue')['default']
    Copy: typeof import('./src/components/popup - Copy/index.vue')['default']
    Lesson: typeof import('./src/components/lesson/index.vue')['default']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    Picker: typeof import('./src/components/picker/index.vue')['default']
    Player: typeof import('./src/components/player/index.vue')['default']
    Popup: typeof import('./src/components/popup/index.vue')['default']
    ProgressBar: typeof import('./src/components/progress-bar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/slider/index.vue')['default']
    Spinner: typeof import('./src/components/spinner/index.vue')['default']
    Tabs: typeof import('./src/components/tabs/index.vue')['default']
    Toast: typeof import('./src/components/toast/index.vue')['default']
  }
}
