/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/button/index.vue')['default']
    Cascader: typeof import('./src/components/cascader/index.vue')['default']
    Checkbox: typeof import('./src/components/checkbox/index.vue')['default']
    CheckboxGroup: typeof import('./src/components/checkbox-group/index.vue')['default']
    Copy: typeof import('./src/components/select - Copy/index.vue')['default']
    DatePicker: typeof import('./src/components/datePicker/index.vue')['default']
    Form: typeof import('./src/components/form/form.vue')['default']
    FormItem: typeof import('./src/components/form/form-item.vue')['default']
    Input: typeof import('./src/components/input/index.vue')['default']
    Lesson: typeof import('./src/components/lesson/index.vue')['default']
    Modal: typeof import('./src/components/modal/index.vue')['default']
    Picker: typeof import('./src/components/picker/index.vue')['default']
    Player: typeof import('./src/components/player/index.vue')['default']
    Popup: typeof import('./src/components/popup/index.vue')['default']
    ProgressBar: typeof import('./src/components/progress-bar/index.vue')['default']
    Radio: typeof import('./src/components/radio/index.vue')['default']
    RadioGroup: typeof import('./src/components/radio-group/index.vue')['default']
    Rate: typeof import('./src/components/rate/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/select/index.vue')['default']
    SettingsPopup: typeof import('./src/components/lesson/settings-popup.vue')['default']
    Slider: typeof import('./src/components/slider/index.vue')['default']
    Spinner: typeof import('./src/components/spinner/index.vue')['default']
    Switch: typeof import('./src/components/switch/index.vue')['default']
    Tabs: typeof import('./src/components/tabs/index.vue')['default']
    Toast: typeof import('./src/components/toast/index.vue')['default']
    VolumePopup: typeof import('./src/components/lesson/volume-popup.vue')['default']
  }
}
